### PR TITLE
Add pigpio and related packages

### LINKED ISSUE #198: Add pigpio to image
Add [`pigpio`](http://abyz.me.uk/rpi/pigpio/) to be pre-installed and running on the image. This should help streamline GPIO control from all programming languages.

### PR DESCRIPTION
**Pull request by zhiquanyeo**
Resolves #198

### CODE REVIEW

**Comment by PeterJohnson** [comment]
E: Unable to locate package python-gpio

**Comment by zhiquanyeo** [comment]
I'm apparently unable to copy-pasta correctly...

**Comment by zhiquanyeo** [comment]
I'm apparently unable to copy-pasta correctly...

**Comment by PeterJohnson** [comment]
Is the non-python3 one also installing python2?  I don’t think we have python2 in the image currently?

**Comment by zhiquanyeo** [comment]
It looks like we install `python python3` in stage2

**Comment by zhiquanyeo** [comment]
Looks like it built, and failed to setup the loopback device

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
