### PR TITLE
Install published pynetworktables wheel from PyPI

### PR DESCRIPTION
**Pull request by PeterJohnson**
Fixed version of #86.

### CODE REVIEW

**Comment by PeterJohnson** [comment]
Just tested and this doesn't work either...

**Comment by auscompgeek** [comment]
... what error message do you get? This can't be right.

**Comment by auscompgeek** [comment]
Any particular reason to not do this?

**Comment by PeterJohnson** [comment]
Closing, this needs to be redone for pyntcore anyways.

**Pull request closed without merging**
